
export const homeTexts = {
  featuredContest: "Concursos activos",
  seeAll: "Ver todos",
  eventTypes: "Fotografía cualquier tipo de evento",
  eventTypesDesc: "Desde eventos musicales y competiciones deportivas hasta monumentos históricos y plazas emblemáticas.",
  musicEvents: "Eventos Musicales",
  musicEventsDesc: "Conciertos, festivales y actuaciones en vivo",
  sportsEvents: "Eventos Deportivos",
  sportsEventsDesc: "Competiciones, carreras y torneos",
  touristPlaces: "Lugares Turísticos",
  touristPlacesDesc: "Monumentos, plazas y atracciones",
  thematicContests: "Concursos Temáticos",
  thematicContestsDesc: "Gastronomía, naturaleza y arte",
  nearbyContests: "Descubre concursos cerca de ti",
  nearbyContestsDesc: "",
  howItWorks: "¿Cómo funciona?",
  participate: "1. Participa",
  participateDesc: "Regístrate y sube tus mejores fotos en concursos cerca de ti.",
  vote: "2. Vota",
  voteDesc: "Vota las mejores fotos",
  win: "3. Gana",
  winDesc: "Gana premios y reconocimiento",
  startNow: "Empezar",
  organizerTitle: "¿Eres organizador?",
  organizerDesc: "Crea concursos fotográficos para tus eventos o promociona tu negocio con la mejor plataforma para concursos fotográficos geolocalizados.",
  discoverPlans: "Descubre nuestros planes",
  heroTitle: "Concursos Fotográficos Geolocalizados",
  heroSubtitle: "Participa, vota y gana en concursos fotográficos cerca de ti",
  heroDescription: "Descubre concursos fotográficos en cualquier parte del mundo. Sube tus mejores fotos y gana increíbles premios.",
  exploreContests: "Explorar concursos",
  winningGallery: "Galería de Fotos Ganadoras",
  winningGalleryDesc: "",
  viewGallery: "Ver Galería Completa"
};
