
export const homeTexts = {
  featuredContest: "Popular Contests",
  seeAll: "See all",
  eventTypes: "Photograph any type of event",
  eventTypesDesc: "From music events and sports competitions to historical monuments and emblematic squares.",
  musicEvents: "Music Events",
  musicEventsDesc: "Concerts, festivals and live performances",
  sportsEvents: "Sports Events",
  sportsEventsDesc: "Competitions, races and tournaments",
  touristPlaces: "Tourist Places",
  touristPlacesDesc: "Monuments, squares and attractions",
  thematicContests: "Thematic Contests",
  thematicContestsDesc: "Gastronomy, nature and art",
  nearbyContests: "Contests near you",
  nearbyContestsDesc: "Explore the map to find contests in your area and easily participate.",
  howItWorks: "How it works?",
  participate: "1. Participate",
  participateDesc: "Register and upload your best photos to active contests near your location.",
  vote: "2. Vote",
  voteDesc: "Explore photos from other participants and vote for your favorites using our voting system.",
  win: "3. Win",
  winDesc: "Winners receive special rewards and recognition from organizers.",
  startNow: "Start now",
  organizerTitle: "Are you an organizer?",
  organizerDesc: "Create photo contests for your events or promote your business with the best platform for geolocated photo contests.",
  discoverPlans: "Discover our plans",
  heroTitle: "Geolocated Photo Contests",
  heroSubtitle: "Participate, vote and win in photo contests near you",
  heroDescription: "Discover photo contests anywhere in the world. Upload your best photos and win amazing prizes.",
  exploreContests: "Explore contests",
  winningGallery: "Winning Photos Gallery",
  winningGalleryDesc: "Explore the best photos from our contests - a showcase of the finest photography talent.",
  viewGallery: "View Full Gallery"
};
