// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhfwrbnjwbuagomvrbvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoZndyYm5qd2J1YWdvbXZyYnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjMxMTcsImV4cCI6MjA1NzUzOTExN30.4u7cnZlZX2bwiAWvwx_xUgPLsV49Uu88ycLLmpqwUh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);