// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sslwwbcvpujyfnpjypwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzbHd3YmN2cHVqeWZucGp5cHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTY1MTAsImV4cCI6MjA2MDQ3MjUxMH0.4lGvPZsJ0GrkUffDwjybfk_K9BcPSdYtaAsclWjD_7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);